apiVersion: v1
kind: PersistentVolume
metadata:
  name: lc-xrp-db-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lc-xrp-db-sc
  hostPath:
    path: /data/postgres
