apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lc-saas-db-pvc
  namespace: lc-saas-ns
spec:
  storageClassName: lc-saas-db-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
