apiVersion: v1
kind: Secret
metadata:
  name: lc-xrp-db-secret
  namespace: lc-xrp-ns
type: Opaque
data:
  postgres-db: bGltcGlk # limpid
  postgres-user: bGltcGlk # limpid
  postgres-password: bGltcGlk # limpid
