apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lc-saas-ingress
  labels:
    name: lc-saas-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: lc-saas-app-service
                port:
                  number: 80
