apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-saas-app-deployment
  labels:
    app: lc-saas-app
  namespace: lc-saas-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lc-saas-app
  template:
    metadata:
      labels:
        app: lc-saas-app
    spec:
      # imagePullSecrets:
      #   - name: lc-saas-app-pull-secret
      containers:
        - name: lc-saas-app
          image: limidcrypto1/lc_xrp:blue
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lc-saas-db-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lc-saas-db-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lc-saas-db-secret
                  key: postgres-password
            - name: DATABASE_URL
              value: postgres://limpid:limpid@lc-saas-db-service:5432/limpid
            - name: REDIS_URL
              value: redis://lc-saas-redis-service:6379
            - name: MAILER_HOST
              value: lc-saas-mailer-service
            - name: SERVER_PORT
              value: "80"
          # - name: USER_DATABASE_URL
          #   value: ""
