apiVersion: v1
kind: Service
metadata:
  name: lc-xrp-app-service
  namespace: lc-xrp-ns
spec:
  selector:
    app: lc-xrp-app
  type: ExternalName
  externalName: lc-xrp-app-service.namespacename.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
