apiVersion: v1
kind: Service
metadata:
  name: lc-saas-app-service
  namespace: lc-saas-ns
spec:
  selector:
    app: lc-saas-app
  type: ExternalName
  externalName: lc-saas-app-service.namespacename.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
