openapi: "3.1.0"
info:
  title: "SAAS API Documentation"
  version: "1.0.0"
  description: "SAAS API Documentation"
  contact:
    name: "SAAS API Documentation"
    email: "contact@limpidcrypto.com"
servers:
  - url: https://api.limpidcrypto.com/api/v1/Test
    description: "Testnet API"
# paths:
#   /wallet/faucet:
#     get:
#       summary: Finds Pets by status
#       description: Multiple status values can be provided with comma separated strings
#       operationId: findPetsByStatus
#       parameters:
#         - name: status
#           in: query
#           description: Status values that need to be considered for filter
#           required: false
#           explode: true
#           schema:
#             type: string
#             default: available
#             enum:
#               - available
#               - pending
#               - sold
#       responses:
#         "200":
#           description: successful operation
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: "#/components/schemas/Pet"
#             application/xml:
#               schema:
#                 type: array
#                 items:
#                   $ref: "#/components/schemas/Pet"
